### ISSUE TITLE
Problem importing gdc19

### ISSUE THREAD

**Issue by edorafa** [OpenGeoVis/GeothermalDesignChallenge#2]
Hi Bane!

I am facing some issues I cannot solve. I am trying to reproduce exactly what you did to get this nice and complex figure. 

It seems that I'm having problem importing gdc19.

Here what I tried:

create a new environment called geo
pip install -r requirements.txt (inside geo environment)
(geo) C:\Users\edora\Documents\GeothermalDesignChallenge-master>python setup.py install

In another approach, I found out the link to directly download the gdc19 package. I mention this because in VS Code when I execute 00-surfaces.py a download is started. But the only descompressed folder is 'drilling'

```
---------------------------------VS Code message running 00-surfaces.py -------------------- 
Download data package... 
Done.
Downloaded data in 561.471 seconds
Decompressing data package...     
Traceback (most recent call last):
  File "c:/Users/edora/Documents/GeothermalDesignChallenge-master/project/data-aggregation/00-surfaces.py", line 13, in <module>
    import gdc19
  File "C:\Users\edora\Anaconda3\envs\geo3\lib\site-packages\gdc19-0.0.0-py3.7.egg\gdc19\__init__.py", line 37, in <module>
    download_data()
  File "C:\Users\edora\Anaconda3\envs\geo3\lib\site-packages\gdc19-0.0.0-py3.7.egg\gdc19\download.py", line 57, in download_data
    zip_ref.extractall(gdc19.USER_DATA_PATH)
  File "C:\Users\edora\Anaconda3\envs\geo3\lib\zipfile.py", line 1619, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\edora\Anaconda3\envs\geo3\lib\zipfile.py", line 1673, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\edora\\AppData\\Local\\gdc19\\gdc19\\PUBLIC_DATA\\drilling\\Icon\r'

------------------------------------------------------------------------------------------------
```
gdc19 package with PUBLIC_DATA inside is downloaded to the follow path: 
`C:\Users\edora\AppData\Local\gdc19\gdc19`

gdc19 has to be moved to another folder? Do you have any clue of what is going on?
```
OS: Windowns 10 64 bit
Python: 3.7.5
Executed in VS Code
```

**Comment by banesullivan** [comment]
Hi @edorafa, thanks for giving this repo a try! It's a bit messy as it was more or less hacked together for the competition in not a whole lot of time, but

This looks like the code I have to automatically download and unzip all of the data is running into an issue on Windows. I've worked entirely with Mac and Linux on this project thus far so some Windows nuance was likely overlooked.

Can you try just activiating Python and `import gdc19`? It should kick off that download without trying to run the examples - this might help track down where the issue lies.

```py
import gdc19
```


If all else fails, maybe just manually download the data from: https://drive.google.com/file/d/1imG1OKlgBYEMb6p-T5mdUH76mGyNdHsE 
and unarchive it in the path `C:\Users\edora\AppData\Local\gdc19\gdc19`

**Comment by edorafa** [comment]
Hi @banesullivan,

I believe that all _omf_ files are missing, as _surfaces.omf_ required in _01-gravity-mesh-refine.py_. No _omf_ files could be found in the link you sent.

Also, does exist another repo that generates the figure in your article published at JOSS?

**Comment by banesullivan** [comment]
That's correct, the scripts aggregate the data from the CSV files given in the GDR to the OMF archives. The workflow has to be run in order: https://github.com/OpenGeoVis/GeothermalDesignChallenge/tree/master/project/data-aggregation

Which is done by installing `gdc19`, then `cd docs` and run `make html` which will run the whole project and produce the aggregated data products as well as the visualizations shown in the gallery: https://forge.pvgeo.org/project/index.html

EDIT: you'll need to also remove all the *.md5 files: `rm -r *.md5`

**Comment by banesullivan** [comment]
> Also, does exist another repo that generates the figure in your article published at JOSS?

The figure you're referring to in [the PyVista publication](https://joss.theoj.org/papers/10.21105/joss.01450) was created from figure 4 in the following script just using a different camera position:
https://forge.pvgeo.org/project/visual-inspection/long-submission-figures.html#figure-4

**Comment by ghost** [comment]
data file link was broken, please help the zip data file url,  thank you.

https://drive.google.com/file/d/1imG1OKlgBYEMb6p-T5mdUH76mGyNdHsE

**Comment by banesullivan** [comment]
Ah sorry, that data file was hosted on an old Google Drive account. I will add it to my Dropbox and post a link here soon

**Comment by rarygit** [comment]
Hi Bane,

Did you have a new link for the  gdc19 data?

Thanks for archiving and documenting the 2019 Challenge. I am using it to understand the OpenGeoVis workflow.

**Comment by rarygit** [comment]
Hi Bane

I have downloaded some of the datasets required for the Challenge from the GDR Utah Forge links.

Could you please upload (preferably) or (alternatively) post the link the GDR Data page to download the temperature probe csv file:

well_based_temperature.csv

Referenced here:

Temperature Probe Data
# Load the temperature data
_temp = pd.read_csv(
            gdc19.get_temperature_path('well_based_temperature.csv')
            )
_temp.head()

https://forge.pvgeo.org/project/data-aggregation/02-temperature.html#sphx-glr-download-project-data-aggregation-02-temperature-py

Thanks

**Comment by banesullivan** [comment]
I've added all of the data to my dropbox here: https://www.dropbox.com/s/oflxskxupj9wlau/data_archive.zip?dl=0

Unfortunately, I do not have the bandwidth to maintain this project but I will do my best to keep the data hosted there for as long as I can.

Otherwise, I am archiving this repository because it would be a significant amount of work to update it to the latest versions of pyvista
